import { ABILITIES, abils } from '../calc/const/const';

const necroAbilityKeys = [
    ABILITIES.NECRO_AUTO,
    ABILITIES.TOUCH_OF_DEATH,
    ABILITIES.SOUL_SAP,
    ABILITIES.CONJURE_UNDEAD_ARMY,
    ABILITIES.CONJURE_SKELETON_WARRIOR,
    ABILITIES.COMMAND_SKELETON_WARRIOR,
    ABILITIES.CONJURE_VENGEFUL_GHOST,
    ABILITIES.CONJURE_PUTRID_ZOMBIE,
    ABILITIES.COMMAND_PUTRID_ZOMBIE,
    ABILITIES.CONJURE_PHANTOM_GUARDIAN,
    ABILITIES.COMMAND_VENGEFUL_GHOST,
    ABILITIES.COMMAND_PHANTOM_GUARDIAN,
    ABILITIES.FINGER_OF_DEATH,
    ABILITIES.DEATHSKULLS_4,
    ABILITIES.SOUL_STRIKE,
    ABILITIES.SOUL_STRIKE_AOE,
    ABILITIES.VOLLEY_OF_SOULS_DYNAMIC,
    ABILITIES.SPECTRAL_SCYTHE_1,
    ABILITIES.SPECTRAL_SCYTHE_2,
    ABILITIES.SPECTRAL_SCYTHE_3,
    ABILITIES.BLOAT,
    ABILITIES.BLOOD_SIPHON,
    ABILITIES.DEATH_GRASP,
    ABILITIES.DEATH_ESSENCE,
    ABILITIES.LIFE_TRANSFER,
    ABILITIES.THREADS_OF_FATE,
    ABILITIES.INVOKE_DEATH,
    ABILITIES.SPLIT_SOUL_NECRO,
    ABILITIES.LIVING_DEATH,
    ABILITIES.AFTERSHOCK_NECRO
];

const abilities = Object.fromEntries(
    necroAbilityKeys.map(key => [key, abils[key]])
);

export { abilities };
