import { ABILITIES, abils } from '../calc/const/const';

const rangedAbilityKeys = [
    ABILITIES.RANGED_AUTO,
    ABILITIES.GREATER_RICOCHET,
    ABILITIES.PIERCING_SHOT,
    ABILITIES.CORRUPTION_SHOT,
    ABILITIES.GALESHOT,
    ABILITIES.IMBUE_SHADOWS,
    ABILITIES.BINDING_SHOT,
    ABILITIES.SNIPE,
    ABILITIES.RICOCHET,
    ABILITIES.RAPID_FIRE,
    ABILITIES.SNAP_SHOT,
    ABILITIES.SHADOW_TENDRILS,
    ABILITIES.BOMBARDMENT,
    ABILITIES.DEADSHOT,
    ABILITIES.CRYSTAL_RAIN,
    ABILITIES.BALANCE_BY_FORCE,
    ABILITIES.DESTRUCTIVE_SHOT,
    ABILITIES.SHADOWFALL,
    ABILITIES.DESCENT_OF_DARKNESS,
    ABILITIES.BALANCED_SHOT,
    ABILITIES.AIMED_SHOT,
    ABILITIES.POWER_SHOT,
    ABILITIES.TWIN_FANG,
    ABILITIES.PHANTOM_STRIKE,
    ABILITIES.HAMSTRING,
    ABILITIES.TWIN_SHOT,
    ABILITIES.CHAIN_HIT,
    ABILITIES.RESTORATIVE_SHOT,
    ABILITIES.SOUL_SHOT,
    ABILITIES.DEEP_BURN,
    ABILITIES.DEFIANCE,
    ABILITIES.BOLG_PROC,
    ABILITIES.AFTERSHOCK_RANGED,
    ABILITIES.DEATHS_SWIFTNESS,
    ABILITIES.GREATER_DEATHS_SWIFTNESS,
    ABILITIES.SPLIT_SOUL_ECB
];

const abilities = Object.fromEntries(
    rangedAbilityKeys.map(key => [key, abils[key]])
);

export { abilities };
