import { ABILITIES, abils } from '../calc/const/const';

const magicAbilityKeys = [
    ABILITIES.MAGIC_AUTO,
    ABILITIES.GREATER_CONCENTRATED_BLAST,
    ABILITIES.DRAGON_BREATH,
    ABILITIES.MAGMA_TEMPEST,
    ABILITIES.CORRUPTION_BLAST,
    ABILITIES.COMBUST,
    ABILITIES.TIME_STRIKE,
    ABILITIES.GREATER_SONIC_WAVE,
    ABILITIES.GREATER_CHAIN,
    ABILITIES.IMPACT,
    ABILITIES.SONIC_WAVE,
    ABILITIES.CONCENTRATED_BLAST,
    ABILITIES.CHAIN,
    ABILITIES.WILD_MAGIC,
    ABILITIES.ASPHYXIATE,
    ABILITIES.SMOKE_CLOUD,
    ABILITIES.SMOKE_TENDRILS,
    ABILITIES.OMNIPOWER,
    ABILITIES.TSUNAMI,
    ABILITIES.CLAWS_OF_GUTHIX,
    ABILITIES.TEMPEST_OF_ARMADYL,
    ABILITIES.IBAN_BLAST,
    ABILITIES.INSTABILITY,
    ABILITIES.RUNE_FLAME,
    ABILITIES.DEVOUR,
    ABILITIES.REAP,
    ABILITIES.SOULFIRE,
    ABILITIES.SARADOMIN_STRIKE,
    ABILITIES.FROM_THE_SHADOWS,
    ABILITIES.FLAMES_OF_ZAMORAK,
    ABILITIES.MIASMIC_BARRAGE,
    ABILITIES.AFTERSHOCK_MAGIC,
    ABILITIES.GLACIAL_EMBRACE_HIT,
    ABILITIES.SUNSHINE,
    ABILITIES.GREATER_SUNSHINE
];

const abilities = Object.fromEntries(
    magicAbilityKeys.map(key => [key, abils[key]])
);

export { abilities };
